# rename this file to values.yaml and pass --local-config=cfg/values.yaml flag to use these values.

title: "little story: the knight"
vsync: false
fps: 60
enable_fps: true
windows_size:
  x: 1920
  y: 960
logging: false